#!/usr/bin/env ruby

require 'gibberish'
require 'colorize'

def trykeys(hash)
  hash = hash.split(":", 2)
  user = hash.first
  phash = hash.last.split(":", 2).first
  salt = hash.last.split(":", 2).last.strip 
  # Open Wordlist
  wlist = File.open(@w).read
  wlist = wlist.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
  f = 0
  i = 1
  wlist.each_line do |w|
    next if f == 1
    pass = w.strip
    x = Gibberish::MD5(pass)
    y = Gibberish::MD5("#{x}#{salt}")
    if y == phash
      entry = "#{user}:#{pass}"
      puts "+ #{entry}".green
      File.open(@o, "a"){|f| f.puts entry}
      f = 1
    end
    i+=1
  end
end

unless ARGV.empty?

  @i, @o, @w = ""

  ARGV.each do |arg|
    a = ARGV.index(arg) + 1

    case arg
      when "-i"
        @i = ARGV[a]
      when "-o"
        @o = ARGV[a]
      when "-w"
        @w = ARGV[a]
    end  
  end
  puts @i, @o, @w
  if @i == "" or @w == ""
    puts "Usage: vbcrack -i <hash file> -o <outfile> -w <wordlist>"
    abort()
  end
  puts "===================================================================".white
  puts "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++".yellow
  puts %[
.##.....##.########...######..########.....###.....######..##....##
.##.....##.##.....##.##....##.##.....##...##.##...##....##.##...##.
.##.....##.##.....##.##.......##.....##..##...##..##.......##..##..
.##.....##.########..##.......########..##.....##.##.......#####...
..##...##..##.....##.##.......##...##...#########.##.......##..##..
...##.##...##.....##.##....##.##....##..##.....##.##....##.##...##.
....###....########...######..##.....##.##.....##..######..##....##
].red
  puts "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++".yellow
  puts "===================================================================".white
  # Open Hash File
  file = File.open(@i).read
  file = file.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
  file.each_line do |l| 
    trykeys(l)
  end
end
