#!/usr/bin/env ruby

@reg3 = /^[a-z0-9A-Z' '.]{1,}:[a-z0-9]{32}:[\s\S]{3}$/
@reg4 = /^[a-z0-9A-Z' '.]{1,}:[a-z0-9]{32}:[\s\S]{30}$/

def grab(l)
  m = l.scan(@reg3)
  File.open("v3.hash", "a"){|f| f.puts m}
  m = l.scan(@reg4)
  File.open("v4.hash", "a"){|f| f.puts m}
end

unless ARGV.empty?
  file = File.open(ARGV[0]).read
  file = file.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
  file.each_line do |l|
    grab(l)
  end
end
